# This is the Copy of Debut Donation Modal backup created on 08/17/2021
development:
  password: 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
  theme_id: "126941855940"
  store: https://seattlechildrenshospital.myshopify.com
